

const githubResult = """
{
  "total_count": 5371,
  "incomplete_results": false,
  "items": [
    {
      "login": "renan",
      "id": 28046,
      "node_id": "MDQ6VXNlcjI4MDQ2",
      "avatar_url": "https://avatars3.githubusercontent.com/u/28046?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renan",
      "html_url": "https://github.com/renan",
      "followers_url": "https://api.github.com/users/renan/followers",
      "following_url": "https://api.github.com/users/renan/following{/other_user}",
      "gists_url": "https://api.github.com/users/renan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renan/subscriptions",
      "organizations_url": "https://api.github.com/users/renan/orgs",
      "repos_url": "https://api.github.com/users/renan/repos",
      "events_url": "https://api.github.com/users/renan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renan/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renancaraujo",
      "id": 6718144,
      "node_id": "MDQ6VXNlcjY3MTgxNDQ=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/6718144?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renancaraujo",
      "html_url": "https://github.com/renancaraujo",
      "followers_url": "https://api.github.com/users/renancaraujo/followers",
      "following_url": "https://api.github.com/users/renancaraujo/following{/other_user}",
      "gists_url": "https://api.github.com/users/renancaraujo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renancaraujo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renancaraujo/subscriptions",
      "organizations_url": "https://api.github.com/users/renancaraujo/orgs",
      "repos_url": "https://api.github.com/users/renancaraujo/repos",
      "events_url": "https://api.github.com/users/renancaraujo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renancaraujo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "h3nnn4n",
      "id": 7543345,
      "node_id": "MDQ6VXNlcjc1NDMzNDU=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/7543345?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/h3nnn4n",
      "html_url": "https://github.com/h3nnn4n",
      "followers_url": "https://api.github.com/users/h3nnn4n/followers",
      "following_url": "https://api.github.com/users/h3nnn4n/following{/other_user}",
      "gists_url": "https://api.github.com/users/h3nnn4n/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/h3nnn4n/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/h3nnn4n/subscriptions",
      "organizations_url": "https://api.github.com/users/h3nnn4n/orgs",
      "repos_url": "https://api.github.com/users/h3nnn4n/repos",
      "events_url": "https://api.github.com/users/h3nnn4n/events{/privacy}",
      "received_events_url": "https://api.github.com/users/h3nnn4n/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renanpalmeira",
      "id": 6018798,
      "node_id": "MDQ6VXNlcjYwMTg3OTg=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/6018798?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renanpalmeira",
      "html_url": "https://github.com/renanpalmeira",
      "followers_url": "https://api.github.com/users/renanpalmeira/followers",
      "following_url": "https://api.github.com/users/renanpalmeira/following{/other_user}",
      "gists_url": "https://api.github.com/users/renanpalmeira/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renanpalmeira/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renanpalmeira/subscriptions",
      "organizations_url": "https://api.github.com/users/renanpalmeira/orgs",
      "repos_url": "https://api.github.com/users/renanpalmeira/repos",
      "events_url": "https://api.github.com/users/renanpalmeira/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renanpalmeira/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renanpallin",
      "id": 18226644,
      "node_id": "MDQ6VXNlcjE4MjI2NjQ0",
      "avatar_url": "https://avatars2.githubusercontent.com/u/18226644?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renanpallin",
      "html_url": "https://github.com/renanpallin",
      "followers_url": "https://api.github.com/users/renanpallin/followers",
      "following_url": "https://api.github.com/users/renanpallin/following{/other_user}",
      "gists_url": "https://api.github.com/users/renanpallin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renanpallin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renanpallin/subscriptions",
      "organizations_url": "https://api.github.com/users/renanpallin/orgs",
      "repos_url": "https://api.github.com/users/renanpallin/repos",
      "events_url": "https://api.github.com/users/renanpallin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renanpallin/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renanrodrigo",
      "id": 15742644,
      "node_id": "MDQ6VXNlcjE1NzQyNjQ0",
      "avatar_url": "https://avatars1.githubusercontent.com/u/15742644?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renanrodrigo",
      "html_url": "https://github.com/renanrodrigo",
      "followers_url": "https://api.github.com/users/renanrodrigo/followers",
      "following_url": "https://api.github.com/users/renanrodrigo/following{/other_user}",
      "gists_url": "https://api.github.com/users/renanrodrigo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renanrodrigo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renanrodrigo/subscriptions",
      "organizations_url": "https://api.github.com/users/renanrodrigo/orgs",
      "repos_url": "https://api.github.com/users/renanrodrigo/repos",
      "events_url": "https://api.github.com/users/renanrodrigo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renanrodrigo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renanbastos93",
      "id": 8202898,
      "node_id": "MDQ6VXNlcjgyMDI4OTg=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/8202898?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renanbastos93",
      "html_url": "https://github.com/renanbastos93",
      "followers_url": "https://api.github.com/users/renanbastos93/followers",
      "following_url": "https://api.github.com/users/renanbastos93/following{/other_user}",
      "gists_url": "https://api.github.com/users/renanbastos93/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renanbastos93/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renanbastos93/subscriptions",
      "organizations_url": "https://api.github.com/users/renanbastos93/orgs",
      "repos_url": "https://api.github.com/users/renanbastos93/repos",
      "events_url": "https://api.github.com/users/renanbastos93/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renanbastos93/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "RenanBorba",
      "id": 48495838,
      "node_id": "MDQ6VXNlcjQ4NDk1ODM4",
      "avatar_url": "https://avatars3.githubusercontent.com/u/48495838?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/RenanBorba",
      "html_url": "https://github.com/RenanBorba",
      "followers_url": "https://api.github.com/users/RenanBorba/followers",
      "following_url": "https://api.github.com/users/RenanBorba/following{/other_user}",
      "gists_url": "https://api.github.com/users/RenanBorba/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/RenanBorba/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/RenanBorba/subscriptions",
      "organizations_url": "https://api.github.com/users/RenanBorba/orgs",
      "repos_url": "https://api.github.com/users/RenanBorba/repos",
      "events_url": "https://api.github.com/users/RenanBorba/events{/privacy}",
      "received_events_url": "https://api.github.com/users/RenanBorba/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renanmpimentel",
      "id": 1204910,
      "node_id": "MDQ6VXNlcjEyMDQ5MTA=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1204910?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renanmpimentel",
      "html_url": "https://github.com/renanmpimentel",
      "followers_url": "https://api.github.com/users/renanmpimentel/followers",
      "following_url": "https://api.github.com/users/renanmpimentel/following{/other_user}",
      "gists_url": "https://api.github.com/users/renanmpimentel/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renanmpimentel/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renanmpimentel/subscriptions",
      "organizations_url": "https://api.github.com/users/renanmpimentel/orgs",
      "repos_url": "https://api.github.com/users/renanmpimentel/repos",
      "events_url": "https://api.github.com/users/renanmpimentel/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renanmpimentel/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renanrboliveira",
      "id": 673991,
      "node_id": "MDQ6VXNlcjY3Mzk5MQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/673991?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renanrboliveira",
      "html_url": "https://github.com/renanrboliveira",
      "followers_url": "https://api.github.com/users/renanrboliveira/followers",
      "following_url": "https://api.github.com/users/renanrboliveira/following{/other_user}",
      "gists_url": "https://api.github.com/users/renanrboliveira/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renanrboliveira/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renanrboliveira/subscriptions",
      "organizations_url": "https://api.github.com/users/renanrboliveira/orgs",
      "repos_url": "https://api.github.com/users/renanrboliveira/repos",
      "events_url": "https://api.github.com/users/renanrboliveira/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renanrboliveira/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "RenanJPaula",
      "id": 3266640,
      "node_id": "MDQ6VXNlcjMyNjY2NDA=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/3266640?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/RenanJPaula",
      "html_url": "https://github.com/RenanJPaula",
      "followers_url": "https://api.github.com/users/RenanJPaula/followers",
      "following_url": "https://api.github.com/users/RenanJPaula/following{/other_user}",
      "gists_url": "https://api.github.com/users/RenanJPaula/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/RenanJPaula/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/RenanJPaula/subscriptions",
      "organizations_url": "https://api.github.com/users/RenanJPaula/orgs",
      "repos_url": "https://api.github.com/users/RenanJPaula/repos",
      "events_url": "https://api.github.com/users/RenanJPaula/events{/privacy}",
      "received_events_url": "https://api.github.com/users/RenanJPaula/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renanmav",
      "id": 43140758,
      "node_id": "MDQ6VXNlcjQzMTQwNzU4",
      "avatar_url": "https://avatars0.githubusercontent.com/u/43140758?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renanmav",
      "html_url": "https://github.com/renanmav",
      "followers_url": "https://api.github.com/users/renanmav/followers",
      "following_url": "https://api.github.com/users/renanmav/following{/other_user}",
      "gists_url": "https://api.github.com/users/renanmav/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renanmav/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renanmav/subscriptions",
      "organizations_url": "https://api.github.com/users/renanmav/orgs",
      "repos_url": "https://api.github.com/users/renanmav/repos",
      "events_url": "https://api.github.com/users/renanmav/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renanmav/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renanmorais",
      "id": 5667924,
      "node_id": "MDQ6VXNlcjU2Njc5MjQ=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/5667924?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renanmorais",
      "html_url": "https://github.com/renanmorais",
      "followers_url": "https://api.github.com/users/renanmorais/followers",
      "following_url": "https://api.github.com/users/renanmorais/following{/other_user}",
      "gists_url": "https://api.github.com/users/renanmorais/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renanmorais/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renanmorais/subscriptions",
      "organizations_url": "https://api.github.com/users/renanmorais/orgs",
      "repos_url": "https://api.github.com/users/renanmorais/repos",
      "events_url": "https://api.github.com/users/renanmorais/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renanmorais/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renanpvaz",
      "id": 14297772,
      "node_id": "MDQ6VXNlcjE0Mjk3Nzcy",
      "avatar_url": "https://avatars0.githubusercontent.com/u/14297772?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renanpvaz",
      "html_url": "https://github.com/renanpvaz",
      "followers_url": "https://api.github.com/users/renanpvaz/followers",
      "following_url": "https://api.github.com/users/renanpvaz/following{/other_user}",
      "gists_url": "https://api.github.com/users/renanpvaz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renanpvaz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renanpvaz/subscriptions",
      "organizations_url": "https://api.github.com/users/renanpvaz/orgs",
      "repos_url": "https://api.github.com/users/renanpvaz/repos",
      "events_url": "https://api.github.com/users/renanpvaz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renanpvaz/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renanivo",
      "id": 136425,
      "node_id": "MDQ6VXNlcjEzNjQyNQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/136425?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renanivo",
      "html_url": "https://github.com/renanivo",
      "followers_url": "https://api.github.com/users/renanivo/followers",
      "following_url": "https://api.github.com/users/renanivo/following{/other_user}",
      "gists_url": "https://api.github.com/users/renanivo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renanivo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renanivo/subscriptions",
      "organizations_url": "https://api.github.com/users/renanivo/orgs",
      "repos_url": "https://api.github.com/users/renanivo/repos",
      "events_url": "https://api.github.com/users/renanivo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renanivo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renanlopescoder",
      "id": 7944072,
      "node_id": "MDQ6VXNlcjc5NDQwNzI=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/7944072?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renanlopescoder",
      "html_url": "https://github.com/renanlopescoder",
      "followers_url": "https://api.github.com/users/renanlopescoder/followers",
      "following_url": "https://api.github.com/users/renanlopescoder/following{/other_user}",
      "gists_url": "https://api.github.com/users/renanlopescoder/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renanlopescoder/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renanlopescoder/subscriptions",
      "organizations_url": "https://api.github.com/users/renanlopescoder/orgs",
      "repos_url": "https://api.github.com/users/renanlopescoder/repos",
      "events_url": "https://api.github.com/users/renanlopescoder/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renanlopescoder/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renanpupin",
      "id": 8743530,
      "node_id": "MDQ6VXNlcjg3NDM1MzA=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/8743530?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renanpupin",
      "html_url": "https://github.com/renanpupin",
      "followers_url": "https://api.github.com/users/renanpupin/followers",
      "following_url": "https://api.github.com/users/renanpupin/following{/other_user}",
      "gists_url": "https://api.github.com/users/renanpupin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renanpupin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renanpupin/subscriptions",
      "organizations_url": "https://api.github.com/users/renanpupin/orgs",
      "repos_url": "https://api.github.com/users/renanpupin/repos",
      "events_url": "https://api.github.com/users/renanpupin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renanpupin/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renanxcortes",
      "id": 22593188,
      "node_id": "MDQ6VXNlcjIyNTkzMTg4",
      "avatar_url": "https://avatars2.githubusercontent.com/u/22593188?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renanxcortes",
      "html_url": "https://github.com/renanxcortes",
      "followers_url": "https://api.github.com/users/renanxcortes/followers",
      "following_url": "https://api.github.com/users/renanxcortes/following{/other_user}",
      "gists_url": "https://api.github.com/users/renanxcortes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renanxcortes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renanxcortes/subscriptions",
      "organizations_url": "https://api.github.com/users/renanxcortes/orgs",
      "repos_url": "https://api.github.com/users/renanxcortes/repos",
      "events_url": "https://api.github.com/users/renanxcortes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renanxcortes/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renanvalentin",
      "id": 2846918,
      "node_id": "MDQ6VXNlcjI4NDY5MTg=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/2846918?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renanvalentin",
      "html_url": "https://github.com/renanvalentin",
      "followers_url": "https://api.github.com/users/renanvalentin/followers",
      "following_url": "https://api.github.com/users/renanvalentin/following{/other_user}",
      "gists_url": "https://api.github.com/users/renanvalentin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renanvalentin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renanvalentin/subscriptions",
      "organizations_url": "https://api.github.com/users/renanvalentin/orgs",
      "repos_url": "https://api.github.com/users/renanvalentin/repos",
      "events_url": "https://api.github.com/users/renanvalentin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renanvalentin/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renanbr",
      "id": 350222,
      "node_id": "MDQ6VXNlcjM1MDIyMg==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/350222?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renanbr",
      "html_url": "https://github.com/renanbr",
      "followers_url": "https://api.github.com/users/renanbr/followers",
      "following_url": "https://api.github.com/users/renanbr/following{/other_user}",
      "gists_url": "https://api.github.com/users/renanbr/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renanbr/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renanbr/subscriptions",
      "organizations_url": "https://api.github.com/users/renanbr/orgs",
      "repos_url": "https://api.github.com/users/renanbr/repos",
      "events_url": "https://api.github.com/users/renanbr/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renanbr/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "RenanKodama",
      "id": 26185587,
      "node_id": "MDQ6VXNlcjI2MTg1NTg3",
      "avatar_url": "https://avatars0.githubusercontent.com/u/26185587?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/RenanKodama",
      "html_url": "https://github.com/RenanKodama",
      "followers_url": "https://api.github.com/users/RenanKodama/followers",
      "following_url": "https://api.github.com/users/RenanKodama/following{/other_user}",
      "gists_url": "https://api.github.com/users/RenanKodama/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/RenanKodama/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/RenanKodama/subscriptions",
      "organizations_url": "https://api.github.com/users/RenanKodama/orgs",
      "repos_url": "https://api.github.com/users/RenanKodama/repos",
      "events_url": "https://api.github.com/users/RenanKodama/events{/privacy}",
      "received_events_url": "https://api.github.com/users/RenanKodama/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renansj",
      "id": 5496098,
      "node_id": "MDQ6VXNlcjU0OTYwOTg=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/5496098?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renansj",
      "html_url": "https://github.com/renansj",
      "followers_url": "https://api.github.com/users/renansj/followers",
      "following_url": "https://api.github.com/users/renansj/following{/other_user}",
      "gists_url": "https://api.github.com/users/renansj/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renansj/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renansj/subscriptions",
      "organizations_url": "https://api.github.com/users/renansj/orgs",
      "repos_url": "https://api.github.com/users/renansj/repos",
      "events_url": "https://api.github.com/users/renansj/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renansj/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "RenanRB",
      "id": 5372518,
      "node_id": "MDQ6VXNlcjUzNzI1MTg=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/5372518?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/RenanRB",
      "html_url": "https://github.com/RenanRB",
      "followers_url": "https://api.github.com/users/RenanRB/followers",
      "following_url": "https://api.github.com/users/RenanRB/following{/other_user}",
      "gists_url": "https://api.github.com/users/RenanRB/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/RenanRB/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/RenanRB/subscriptions",
      "organizations_url": "https://api.github.com/users/RenanRB/orgs",
      "repos_url": "https://api.github.com/users/RenanRB/repos",
      "events_url": "https://api.github.com/users/RenanRB/events{/privacy}",
      "received_events_url": "https://api.github.com/users/RenanRB/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renanvy",
      "id": 2266325,
      "node_id": "MDQ6VXNlcjIyNjYzMjU=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/2266325?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renanvy",
      "html_url": "https://github.com/renanvy",
      "followers_url": "https://api.github.com/users/renanvy/followers",
      "following_url": "https://api.github.com/users/renanvy/following{/other_user}",
      "gists_url": "https://api.github.com/users/renanvy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renanvy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renanvy/subscriptions",
      "organizations_url": "https://api.github.com/users/renanvy/orgs",
      "repos_url": "https://api.github.com/users/renanvy/repos",
      "events_url": "https://api.github.com/users/renanvy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renanvy/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renanoliveira",
      "id": 421532,
      "node_id": "MDQ6VXNlcjQyMTUzMg==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/421532?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renanoliveira",
      "html_url": "https://github.com/renanoliveira",
      "followers_url": "https://api.github.com/users/renanoliveira/followers",
      "following_url": "https://api.github.com/users/renanoliveira/following{/other_user}",
      "gists_url": "https://api.github.com/users/renanoliveira/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renanoliveira/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renanoliveira/subscriptions",
      "organizations_url": "https://api.github.com/users/renanoliveira/orgs",
      "repos_url": "https://api.github.com/users/renanoliveira/repos",
      "events_url": "https://api.github.com/users/renanoliveira/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renanoliveira/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Renanthea",
      "id": 24597789,
      "node_id": "MDQ6VXNlcjI0NTk3Nzg5",
      "avatar_url": "https://avatars1.githubusercontent.com/u/24597789?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Renanthea",
      "html_url": "https://github.com/Renanthea",
      "followers_url": "https://api.github.com/users/Renanthea/followers",
      "following_url": "https://api.github.com/users/Renanthea/following{/other_user}",
      "gists_url": "https://api.github.com/users/Renanthea/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Renanthea/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Renanthea/subscriptions",
      "organizations_url": "https://api.github.com/users/Renanthea/orgs",
      "repos_url": "https://api.github.com/users/Renanthea/repos",
      "events_url": "https://api.github.com/users/Renanthea/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Renanthea/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucasrenan",
      "id": 114986,
      "node_id": "MDQ6VXNlcjExNDk4Ng==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/114986?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucasrenan",
      "html_url": "https://github.com/lucasrenan",
      "followers_url": "https://api.github.com/users/lucasrenan/followers",
      "following_url": "https://api.github.com/users/lucasrenan/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucasrenan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucasrenan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucasrenan/subscriptions",
      "organizations_url": "https://api.github.com/users/lucasrenan/orgs",
      "repos_url": "https://api.github.com/users/lucasrenan/repos",
      "events_url": "https://api.github.com/users/lucasrenan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucasrenan/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renangabriel27",
      "id": 10130724,
      "node_id": "MDQ6VXNlcjEwMTMwNzI0",
      "avatar_url": "https://avatars1.githubusercontent.com/u/10130724?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renangabriel27",
      "html_url": "https://github.com/renangabriel27",
      "followers_url": "https://api.github.com/users/renangabriel27/followers",
      "following_url": "https://api.github.com/users/renangabriel27/following{/other_user}",
      "gists_url": "https://api.github.com/users/renangabriel27/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renangabriel27/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renangabriel27/subscriptions",
      "organizations_url": "https://api.github.com/users/renangabriel27/orgs",
      "repos_url": "https://api.github.com/users/renangabriel27/repos",
      "events_url": "https://api.github.com/users/renangabriel27/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renangabriel27/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renanferr",
      "id": 41403762,
      "node_id": "MDQ6VXNlcjQxNDAzNzYy",
      "avatar_url": "https://avatars1.githubusercontent.com/u/41403762?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renanferr",
      "html_url": "https://github.com/renanferr",
      "followers_url": "https://api.github.com/users/renanferr/followers",
      "following_url": "https://api.github.com/users/renanferr/following{/other_user}",
      "gists_url": "https://api.github.com/users/renanferr/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renanferr/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renanferr/subscriptions",
      "organizations_url": "https://api.github.com/users/renanferr/orgs",
      "repos_url": "https://api.github.com/users/renanferr/repos",
      "events_url": "https://api.github.com/users/renanferr/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renanferr/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "renanmedina",
      "id": 10059323,
      "node_id": "MDQ6VXNlcjEwMDU5MzIz",
      "avatar_url": "https://avatars1.githubusercontent.com/u/10059323?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renanmedina",
      "html_url": "https://github.com/renanmedina",
      "followers_url": "https://api.github.com/users/renanmedina/followers",
      "following_url": "https://api.github.com/users/renanmedina/following{/other_user}",
      "gists_url": "https://api.github.com/users/renanmedina/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renanmedina/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renanmedina/subscriptions",
      "organizations_url": "https://api.github.com/users/renanmedina/orgs",
      "repos_url": "https://api.github.com/users/renanmedina/repos",
      "events_url": "https://api.github.com/users/renanmedina/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renanmedina/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
} """;